# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cipp2w6m3

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  # Path to the zip package we will create
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'cipp-api.zip'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Archive functions app into zip'
        run: |
          zip -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} .

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'cipp2w6m3'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7C8C17346ECE44B1A393C8EAFCC49F51 }}
